name: 'Change Date Everyday'

on:
  push:
    branches:
      - main
    paths:
      - 'TEMPLATE.md'
      - 'index.js'
  schedule:
    # 时区是UTC世界，我们中国在东八区，所以要加8
    # 下面指我们这的凌晨5点
    # - cron: '0 21 * * *'
    # 早上9点触发把
    # - cron: '0 1 * * *'
    # UTC时间触发
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # git啥的
      - uses: actions/checkout@v2
      # 安装node
      - uses: actions/setup-node@v4
        with:
          # 要装就装最新稳定版
          node-version: '18'
          cache: 'yarn'
      - name: generate README.md
        run: yarn install --prod && yarn start
      - name: git commit files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: icebreaker-bot
          author_email: 1324318532@qq.com
          add: '*.md'
